default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mass_media_development
  username: postgres
  password: 3441

test:
  <<: *default
  database: mass_media_test
  username: postgres
  password: 3441  

